### ISSUE TITLE
Problem with some components 

### ISSUE THREAD

**Issue by merlinnusr** [laravel-frontend-presets/bulma#26]
The styles doesn't apply for inputs, I didn't modify any of login.blade.php
![image](https://user-images.githubusercontent.com/14082302/58755201-2e6e6300-84a4-11e9-878a-05cdfff276a7.png)

I notice also that I have an old version of Bulma but I don't know it is normal.
![image](https://user-images.githubusercontent.com/14082302/58755235-121ef600-84a5-11e9-98d8-b2671d76984a.png)

I followed this tutorial https://github.com/laravel-frontend-presets/bulma#usage, it doens't work

**Comment by robertgarrigos** [comment]
I'm having the same problem and found a work around to fix it.

This composer package is installing the node bulma module 0.7.5, as it's setting a dev dependency in package.json as:

```
"bulma": "^0.7.4",
````
which allows node to install the latest package before 0.8, and the problem is that 0.7.5, which is the one installing right now, is triggering the bug. You just need to change your package.json file as:

```
"bulma": "0.7.4",
```
So it will install exactly 0.7.4 version, which is working fine.

**Comment by robertgarrigos** [comment]
I don't know why, but this line:

https://github.com/laravel-frontend-presets/bulma/blob/88f6c5ff3cc21f0b3c1aed17d639ff60bd48aca7/src/bulma-stubs/bulma.sass#L14

which fixes the problem with bulma, is not present in the composer package installed by the composer require command.

thus, instead of using bulma 0.7.4, better add this line
https://github.com/laravel-frontend-presets/bulma/blob/88f6c5ff3cc21f0b3c1aed17d639ff60bd48aca7/src/bulma-stubs/bulma.sass#L14

to your resources/sass/bulma.sass file

**Comment by robertgarrigos** [comment]
This is strange. I don't know how composer works, but something is wrong with it. I required bulma preset as usual and this is the composer.lock file generated:

```
 "name": "laravel-frontend-presets/bulma",
            "version": "v2.0.4",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel-frontend-presets/bulma.git",
                "reference": "a857f1569f3153c0bee7e9ef130f0aae832b7b6f"
```
the version pulled off seems to be correct, but in fact the reference number is of a couple of commits before, so that's why it doesn't contain the updates to bulma 0.7.5.

**Comment by robertgarrigos** [comment]
I see, it's not composer problem. The reference number is ok. It is the 2.0.4 release, which does not include the changes applied with the commit 88f6c5ff3cc21f0b3c1aed17d639ff60bd48aca7. 
@Laraveldeep would need to create a new release with that commit.

**Comment by robertgarrigos** [comment]
thanks @m1guelpf

**Comment by robertgarrigos** [comment]
I don't know how long it takes packagist.org to update their packages. If you need to update the bulma package you can also do:

```
composer require laravel-frontend-presets/bulma:dev-master
```
do a `npm update` also and `artisan preset bulma-auth`to get latest bulma

**Comment by deeshrestha** [comment]
@robertgarrigos Sorry was travelling. Didn't get time to check this. I have updated the Packagist. 
Thanks @m1guelpf
